"""Pydantic schemas."""

from core.schemas.auth import (
    LogoutRequest,
    MagicConsumeRequest,
    MagicConsumeResponse,
    MagicLinkRequest,
    MergeCartPayload,
    MergeCartItem,
    OkResponse,
    ProfilePayload,
    RefreshTokenRequest,
    RefreshTokenResponse,
)
from core.schemas.admin import (
    CategoryCreateSchema,
    CategoryUpdateSchema,
    ItemCreateSchema,
    ItemImageCreateSchema,
    ItemImageUpdateSchema,
    ItemUpdateSchema,
    OrderStatusUpdateSchema,
    TagCreateSchema,
    TagUpdateSchema,
    UserAdminUpdateSchema,
    VariantCreateSchema,
    VariantUpdateSchema,
)
from core.schemas.base import ErrorDetails, ErrorResponse
from core.schemas.cart import (
    CartItemSchema,
    CartMergeResponse,
    CartMergeWarning,
    CartResponse,
    CartSchema,
    CartTotalsSchema,
)
from core.schemas.catalog import (
    CategoryListResponse,
    CategorySchema,
    ItemDetailSchema,
    ItemDetailResponse,
    ItemImageSchema,
    ItemListSchema,
    TagListResponse,
    TagSchema,
    VariantSchema,
)
from core.schemas.order import (
    OrderContactSchema,
    OrderDeliverySchema,
    OrderEventSchema,
    OrderItemSchema,
    OrderResponse,
    OrderSchema,
)
from core.schemas.pagination import DataResponse, PaginatedResponse
from core.schemas.user import UserResponse, UserSchema, UserUpdateSchema

__all__ = [
    "ErrorDetails",
    "ErrorResponse",
    "CategorySchema",
    "CategoryListResponse",
    "TagSchema",
    "TagListResponse",
    "VariantSchema",
    "ItemImageSchema",
    "ItemListSchema",
    "ItemDetailSchema",
    "ItemDetailResponse",
    "UserSchema",
    "UserUpdateSchema",
    "UserResponse",
    "CartItemSchema",
    "CartTotalsSchema",
    "CartSchema",
    "CartResponse",
    "CartMergeWarning",
    "CartMergeResponse",
    "OrderItemSchema",
    "OrderEventSchema",
    "OrderDeliverySchema",
    "OrderContactSchema",
    "OrderSchema",
    "OrderResponse",
    "DataResponse",
    "PaginatedResponse",
    "MagicLinkRequest",
    "ProfilePayload",
    "MergeCartItem",
    "MergeCartPayload",
    "MagicConsumeRequest",
    "MagicConsumeResponse",
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "LogoutRequest",
    "OkResponse",
    "CategoryCreateSchema",
    "CategoryUpdateSchema",
    "TagCreateSchema",
    "TagUpdateSchema",
    "ItemCreateSchema",
    "ItemUpdateSchema",
    "ItemImageCreateSchema",
    "ItemImageUpdateSchema",
    "VariantCreateSchema",
    "VariantUpdateSchema",
    "OrderStatusUpdateSchema",
    "UserAdminUpdateSchema",
]
